# Generated by Django 4.2.2 on 2023-06-24 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Years of experience must be a positive number."
                    ),
                    django.core.validators.MaxValueValidator(
                        50, message="Years of experience cannot exceed 50."
                    ),
                ]
            ),
        ),
    ]
